version: "3"
services:
  react:
    build:
      context: ../
      dockerfile: ./docker/react/Dockerfile
    image: practice-next-react
    container_name: practice-next-react
    command: npm run dev
    volumes:
      - ../react/:/app
    ports:
      - "8080:3000"

  postgres:
    build:
      context: ../
      dockerfile: ./docker/postgres/Dockerfile
    image: practice-next-postgres
    container_name: practice-next-postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin-pass
    ports:
      - 5432:5432

  rails:
    build:
      context: ../
      dockerfile: ./docker/rails/Dockerfile
    image: practice-next-rails
    container_name: practice-next-rails
    tty: true
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ../rails:/app
      - ../rails/vendor/bundle:/app/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - postgres
