version: "3"
services:
  react:
    build:
      context: ../
      dockerfile: ./docker/react/Dockerfile
    image: practice-next-react
    container_name: practice-next-react
    tty: true
    volumes:
      - ../react/:/app
    ports:
      - "8080:3000"
